spring:
  application:
    name: txx

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stablecoin?serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 逻辑删除字段
      logic-delete-value: 1 # 已删除的值
      logic-not-delete-value: 0 # 未删除的值

server:
  servlet:
    session:
      timeout: 1d

logging:
  level:
    root: info
    com.bosc.txx: info
